import type { Page, Locator } from '@playwright/test';

export class ChatGPTPage {
  readonly page: Page;
  readonly promptInput: Locator;
  readonly sendButton: Locator;
  readonly lastResponse: Locator;
  readonly projectSidebar: Locator;

  constructor(page: Page) {
    this.page = page;
    this.promptInput = page.locator('#prompt-textarea');
    this.sendButton = page.locator('button[data-testid="send-button"]');
    this.lastResponse = page.locator('div[data-testid^="conversation-turn-"] .markdown').last();
    this.projectSidebar = page.locator('nav');
  }

  async goto() {
    await this.page.goto('https://chatgpt.com');
  }

  async sendPrompt(prompt: string) {
    await this.promptInput.fill(prompt);
    await this.sendButton.click();
  }

  async getResult() {
    await this.lastResponse.waitFor({ state: 'visible' });
    return await this.lastResponse.innerText();
  }

  async downloadImages() {
    // Logic for downloading images from the chat
    const images = this.page.locator('img[alt^="Generated by DALL-E"]');
    const count = await images.count();
    for (let i = 0; i < count; i++) {
      const img = images.nth(i);
      const src = await img.getAttribute('src');
      if (src) {
        // Handle download logic here
        console.log(`Downloading image from: ${src}`);
      }
    }
  }

  async accessProjects() {
    // Logic to navigate to projects
    // ChatGPT recently added 'Projects' for Team/Enterprise users
    await this.page.click('text=Projects');
  }
}
